[package]
name = "axum_helper"
version = "0.1.0"
edition = "2021"
[dependencies]
axum = {version="0.6.10", features = ["json"]}
tokio = { version="1.26.0", features = ["full"]}
serde = { version="1.0.154", features = ["derive"] }
serde_json = "1.0.94"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
validator = { version = "0.16.0", features = ["derive"] }
validator_derive = "0.16.0"
tower-http= { version ="0.4.0", features=["full"] }
askama = "0.12.0"
rust-embed = "6.6.0"
mime_guess ="2.0.4"